name: Run tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: create source archive
      run: |
        git archive ${{ github.ref_name }} --output=dotfiles.tgz

    - name: Build Docker image
      run: |
        docker build --platform linux/amd64 -t alpine-tests --file=containers/alpine .

    - name: Start Docker container and copy files
      run: |
        docker run --rm -it -d --name test_container alpine-tests
        docker cp dotfiles.tgz test_container:/home/tester/src/

    - name: Install dotfiles
      run: |
        docker exec test_container sh -c "tar -xf dotfiles.tgz"
        docker exec test_container sh -c "./make.el"
        docker exec test_container sh -c 'stow -t $HOME emacs'

    - name: Run tests with bats
      run: |
        docker exec -it test_container sh -c "cd /home/tester/src/tests && ./run_tests.bats"
        ls